/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal install. It is committed here
// so the TypeScript scaffold works before dependencies are installed.

